##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  guns配置  ###################
guns:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: true #是否开启登录时验证码 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: true #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  项目启动端口  ###################
server:
  port: 8080
  context-path: /

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false

###################  fido-rest接口配置   ################
u2f-rest:
  #local-url: http://localhost:8080/WayU2FServer/wayfidoapi/v1/
  local-url: https://localhost:8443/WayFido2Server/wayfido2rest/
  dev-url: http://39.104.18.117:8080/WayU2FServer/wayfidoapi/
  #pro-url: https://u2f.whoareyou.live/wayfidoapi/
  pro-url: https://fido2.whoareyou.live/wayfido2rest/

###################  互啊佑软件路径配置  ###################
WAYSoftware:
 #生产环境 
  proFilePath: /opt/tomcat8/webapps/ROOT/WAYSoftware
  proDownloadPath: https://www.whoareyou.live/WAYSoftware
 #测试环境
  devFilePath: /home/tomcat/apache-tomcat-default/webapps/ROOT/WAYSoftware
  devDownloadPath: http://39.104.18.117:8080/WAYSoftware

###################  spring配置  ###################
spring:
  redis:
    host: localhost
    port: 6379
    password:
  profiles:
    active: produce
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 150MB #最大请求大小
      max-file-size: 150MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.modular.system.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---
##########################################################
###################  本地环境的profile  ###################
##########################################################
spring:
  profiles: local
  datasource:
      url: jdbc:mysql://39.104.18.117:3306/guns_db_way?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: WAY@abc123
      filters: log4j,wall,mergeStat

  #本地环境添加fido2中rp多数据源配置
  muti-rp-datasource:
    url: jdbc:mysql://localhost:3306/fido_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 1234
---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://39.104.18.117:3306/guns_db_way?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: WAY@abc123
      filters: log4j,wall,mergeStat
    
#flowable数据源和多数据源配置
guns:
  flowable:
    datasource:
      url: jdbc:mysql://39.104.18.117:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: WAY@abc123
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://39.104.18.117:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: WAY@abc123

  #开发环境添加fido2中rp多数据源配置
  muti-rp-datasource:
    url: jdbc:mysql://39.104.18.117:3306/fido_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: WAY@abc123
    
logging:
  level.root: info
  level.com.stylefeng: info
  path: logs/                          #本地环境日志位置
  #path: ../webapps/guns-admin/logs/   #测试环境日志位置
  file: guns-admin.log
---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://rm-bp1wcewx09y9laon3ho.mysql.rds.aliyuncs.com:3306/guns_db_way?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: DB@whoareyou&224610
      filters: log4j,wall,mergeStat

  #正式环境添加fido2中rp多数据源配置
  muti-rp-datasource:
    url: jdbc:mysql://rm-bp1wcewx09y9laon3ho.mysql.rds.aliyuncs.com:3306/way_u2f_server_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: DB@whoareyou&224610

logging:
  level.root: warn
  path: logs/
  file: guns-admin.log

