language: java

branches:
  except:
    - /tmp-?.*/

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11

script:
  - ./gradlew check assembleJavadoc

stages:
  - test
  - mutation-test

jobs:
  include:
    - stage: mutation-test
      jdk: oraclejdk11
      script: ./gradlew pitest coveralls
